slam_toolbox:
  ros__parameters:
    use_lifecycle_manager: true
    odom_frame: odom
    map_frame: map
    base_frame: base_footprint
    scan_topic: /scan
    map_update_interval: 2.0
    map_start_pose: [0.0, 0.0, 0.0]
